# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e79ae9512361108c34be6c091c32bf056937d306183e14645a7c5bbe83174374c82443a85252fc9dfb9e70f7914ae8195e5e99abb9b418e7250d04a7e2308044

test:
  secret_key_base: a4d91fb8aee11923da3836e75713912db4f0a2aa3162f469f4f3fe6f9a4e04840b3771d783b75f56e6df8fba0f16d4351fa7ffc846dbff38f93c5b3841d34020

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
